accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.create_user, name='signup'),
]

notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("viewnote/<int:pk>", views.view_note, name="view_note"),
    path("editnote/<int:note_id>/", views.edit_note, name="edit_note"),
    path("deletenote/<int:pk>", views.delete_note, name="delete_note"),
    path("api/notes/<int:note_id>/", views.get_note_data, name="get_note_data"),
    # path("api/notes/<int:pk>/", views.api_notes, name="api_notes"),
]

todonotes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('',include('notes.urls',namespace="notes")),
]

templates/partials/footer.html
<footer class="footer bg-dark py-3 text-bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h4 class="text-bg-dark">TodoNote</h4>
        <p class="text-bg-dark">Your trusted platform for managing tasks and notes.</p>
        <p class="text-bg-dark">Made with ❤️</p>
      </div>
      <div class="col-md-4">
        <h4 class="text-bg-dark">Explore</h4>
        <ul class="list-unstyled text-bg-dark">
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'notes:about' %}">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h4 class="text-bg-dark">Connect with Us</h4>
        <ul class="list-unstyled">
          <li><a href="https://www.linkedin.com/in/moti9"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
          <li><a href="https://www.github.com/moti9"><i class="fab fa-linkedin"></i> Github</a></li>
          <li><a href="https://www.twitter.com/moti_kumar_"><i class="fab fa-twitter"></i> Twitter</a></li>
          <li><a href="https://instagram.com/moti9_m"><i class="fab fa-instagram"></i> Instagram</a></li>
          <li><a href="https://www.facebook.com/moti9.m/"><i class="fab fa-facebook"></i> Facebook</a></li>
        </ul>
      </div>
    </div>
    <hr class="bg-dark">
    <div class="row">
      <div class="col-12 text-center">
        <p class="text-bg-dark">&copy; 2023 TodoNote</p>
        <p class="text-bg-dark">Contact us at: <a href="mailto:contact@todonote.com">contact@todonote.com</a></p>
      </div>
    </div>
  </div>
</footer>

templates/partials/navbar.html
{% load static %}

<style>
    .nav-link {
        transition: color 0.3s;
    }

    .nav-item .nav-link:hover,
    .navbar-nav .nav-link:hover {
        color: rgb(0, 0, 255);
    }

    .navbar-brand img {
        transition: transform 0.3s;
    }

    .navbar-brand img:hover {
        transform: scale(1.2);
    }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top py-2 fw-bold">
    <div class="container">
        <a class="navbar-brand" href="{% url 'notes:home' %}">
            <img src="{% static 'images/todo.gif' %}" alt="todo logo" style="width: 1.5rem;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'notes:about' %}">About</a>
                </li>
            </ul>
            <div class="navbar-nav">
                {% if request.user.is_authenticated %}
                <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
                <a class="nav-link active" href="{% url 'accounts:signup' %}">Signup</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>